### ISSUE TITLE
program and postfix_queueid always empty

### ISSUE THREAD

**Issue by erikassuncao** [ActionScripted/elastic-kibana-postfix#1]
Hi,

I'd like to know if does anyone know how to fix it? This is how my postfix log looks like today:

> Oct 10 14:33:41 relay08 postfix/smtpd[15153]: connect from 200-193-225-105.domain.net.br[200.193.225.105]
Oct 10 14:33:41 relay08 postfix/smtpd[15153]: 5774C542888: client=200-193-225-105.domain.net.br[200.193.225.105]
Oct 10 14:33:41 relay08 postfix/cleanup[15625]: 5774C542888: message-id=<7816b1ea6e3f35630630992aa08e270c@domain.com.br>
Oct 10 14:33:41 relay08 postfix/qmgr[1224]: 5774C542888: from=<mail@domain.com.br>, size=70558, nrcpt=1 (queue active)
Oct 10 14:33:41 relay08 postfix/smtpd[15153]: disconnect from 200-193-225-105.domain.net.br[200.193.225.105] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Oct 10 14:33:41 relay08 postfix/smtp[15069]: connect to gmail-smtp-in.l.google.com[2800:3f0:4003:c01::1a]:25: Network is unreachable
Oct 10 14:33:41 relay08 postfix/smtpd[15153]: connect from 200-193-225-105.domain.net.br[200.193.225.105]
Oct 10 14:33:41 relay08 postfix/smtpd[15153]: 6D56C54288B: client=200-193-225-105.domain.net.br[200.193.225.105]
Oct 10 14:33:41 relay08 postfix/cleanup[15625]: 6D56C54288B: message-id=<bb5ce2823d9a604fe734dbc5b6b1760c@domain.com.br>
Oct 10 14:33:41 relay08 postfix/qmgr[1224]: 6D56C54288B: from=<mail@domain.com.br>, size=88167, nrcpt=1 (queue active)

**Comment by ActionScripted** [comment]
@erikassuncao I'm not sure what the issue is. Do you mind explaining a bit? I'm not sure this is related to this project/repo, but I'm happy to help.

**Comment by erikassuncao** [comment]
Actually I made a mistake. It is working fine now. Thank you!
