### ISSUE TITLE
Set fielddata=true on [beat.hostname]

### ISSUE THREAD

**Issue by nicolasbadia** [ActionScripted/elastic-kibana-postfix#2]
First, thanks for sharing this!

I followed the instructions, but I get this error :

`Fielddata is disabled on text fields by default. Set fielddata=true on [beat.hostname] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.`

Also, the dashboard looks like this, with shards failing :

<img width="1049" alt="capture d ecran 2019-01-28 a 02 16 05" src="https://user-images.githubusercontent.com/477089/51809640-bd733080-22a2-11e9-9afe-a3144eadbd61.png">

Any idea of what I missed?

Note that the only thing I changed is that I defined this as output:

```
else if [postfix] {
    elasticsearch {
      hosts => localhost
      manage_template => false
      index => "%{[@metadata][beat]}-postfix-%{[@metadata][version]}-%{+yyyy.MM}-%{[host][name]}"
    }
  }

```
Also no that I'm using nginx and mysql plugins.

**Comment by ActionScripted** [comment]
Glad someone's using this!

Taking at a look at the error I wonder if maybe file beat has changed how they're handling host names. From the config(s) we're using `beat.hostname` but it sounds like maybe that field has changed or is different than the code in this repo is expecting.

To troubleshoot, I'd suggest deleting all resources created by this repo (anything with a name that includes "[Filebeat Postfix]"), check your Filebeat field names and configuration and then edit the files you're using from the repo to use the newer Filebeat field name(s) if they're different.

I might also check any customizations made to logstash or filebeat. Going through the Elastic forums it does look like other folks have had a similar issue in the past but the resolution doesn't seem clear: https://discuss.elastic.co/t/kibana-dashboard-error-set-fielddata-true-on-fieldname/82812/12

The changes you've made should be totally fine; I don't think this error is related to those.

**Comment by nicolasbadia** [comment]
Thanks a lot for the quick answer.
I did a few changes and it is now working properly.

I think the main issue were that my logstash config files were not in a proper order.

Also, looks like my index `"%{[@metadata][beat]}-postfix-%{[@metadata][version]}-%{+yyyy.MM}-%{[host][name]}"` were problematic. `"%{[@metadata][beat]}-%{[@metadata][version]}-%{+yyyy.MM}-%{[host][name]}-postfix"` fixed an issue.

The only not working visualization is "Message total" which say: `Could not locate that index-pattern-field (id: postfix_queueid)`

<img width="219" alt="capture d ecran 2019-01-28 a 10 36 06" src="https://user-images.githubusercontent.com/477089/51826964-9a6b6f80-22e8-11e9-995c-bc74a61b836f.png">

Any idea for this last issue ?

**Comment by nicolasbadia** [comment]
Is this normal?

<img width="835" alt="capture d ecran 2019-01-28 a 10 40 24" src="https://user-images.githubusercontent.com/477089/51827212-28475a80-22e9-11e9-9986-690d42298c7c.png">

**Comment by nicolasbadia** [comment]
Found it, just add to refresh the indexes...
Awesome dashboard by the way 👍

**Comment by ActionScripted** [comment]
@nicolasbadia thanks for following up with the fix! Glad it's working.

**Comment by li-adrienloiseau** [comment]
Hello @nicolasbadia / @ActionScripted  can you share you're configuration ?
I'm in the same issue... 
1. Could not locate that index-pattern-field (id: postfix_queueid)
2. beat.hostname is empty

**Comment by phuongkhpt** [comment]
![image](https://user-images.githubusercontent.com/25604154/86323288-c66deb80-bc66-11ea-948e-24e2dbe16030.png)
![image](https://user-images.githubusercontent.com/25604154/86323307-cff75380-bc66-11ea-8906-84ae70160b76.png)
Pls help me

**Comment by ActionScripted** [comment]
@phuongkhpt have you tried making the changes suggested in the red areas for `fieldata=true`? What version(s) of the Elastic components are you using?
