### ISSUE TITLE
Elasticsearch 7x - "beat.hostname" deprecated

### ISSUE THREAD

**Issue by jtryon** [ActionScripted/elastic-kibana-postfix#5]
https://www.elastic.co/guide/en/beats/libbeat/current/breaking-changes-7.0.html
Got replaced with "agent.hostname".

Apparently a bunch of field names got updated.  Ended up just editing the fields until it seemed to work as intended.  Great lil project btw!  Thanks. : )

**Comment by ActionScripted** [comment]
There have been a few PRs submitted that should address this issue. Please give them a try and let us know how things go.

**Comment by merit-mthompson** [comment]
Closing unless there's something else we need to test/check.

**Comment by ActionScripted** [comment]
https://github.com/ActionScripted/elastic-kibana-postfix/issues/5
